In [92]:
# Q1. Start by loading the IRIS dataset. [Dataset Link:
# Iris Flower Dataset
# A. Display the following information:
# • First 10 rows
# • Shape & Data types
# • Summary statistics (mean, std, min, max)

In [ ]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\lenovo\appdata\roaming\python\python314\site-packages (2.4.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
%pip install pandas matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lenovo\appdata\roaming\python\python314\site-packages (3.0.1)
Requirement already satisfied: matplotlib in c:\users\lenovo\appdata\roaming\python\python314\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\lenovo\appdata\roaming\python\python314\site-packages (0.13.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [95]:
import numpy as np
import pandas as pd

In [96]:
df = pd.read_csv("IRIS.csv")

In [97]:

print(df)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [98]:
# • First 10 rows
df.head(20)

    sepal_length  sepal_width  petal_length  petal_width      species
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
15           5.7          4.4           1.5          0.4  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa
17           5.1          3.5           1.4          0.3  Iris-setosa
18           5.7          3.8           1.7          0.3  Iris-setosa
19           5.1          3.8           1.5          0.3  Iris-setosa

In [99]:
# • Shape & Data types
df.shape

(150, 5)

In [100]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [101]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [102]:
# • Summary statistics (mean, std, min, max)
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [103]:
# B. Select only those rows where:
# • petal_length > 4.5
# • species = "Iris-virginica"

In [104]:
# • petal_length > 4.5
df[df["petal_length"] > 4.5]

     sepal_length  sepal_width  petal_length  petal_width          species
50            7.0          3.2           4.7          1.4  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor
54            6.5          2.8           4.6          1.5  Iris-versicolor
56            6.3          3.3           4.7          1.6  Iris-versicolor
58            6.6          2.9           4.6          1.3  Iris-versicolor
..            ...          ...           ...          ...              ...
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

[63 rows x 5 columns]

In [105]:
# • species = "Iris-virginica"
df[df["species"] == "Iris-virginica"]

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
106           4.9          2.5           4.5          1.7  Iris-virginica
107           7.3          2.9           6.3          1.8  Iris-virginica
108           6.7          2.5           5.8          1.8  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
110           6.5          3.2           5.1          2.0  Iris-virginica
111           6.4          2.7           5.3          1.9  Iris-virginica
112           6.8          3.0           5.5          2.1  Iris-virginica
113           5.7          2.5           5.0          2.0  Iris-virginica
114           5.8          2.8           5.1          2.4  Iris-virginica
115           6.4          3.2           5.3          2.3  Iris-virginica
116           6.5          3.0           5.5          1.8  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
119           6.0          2.2           5.0          1.5  Iris-virginica
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [106]:
df[(df["species"] == "Iris-virginica") | (df["petal_length"] > 4.5)]

     sepal_length  sepal_width  petal_length  petal_width          species
50            7.0          3.2           4.7          1.4  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor
54            6.5          2.8           4.6          1.5  Iris-versicolor
56            6.3          3.3           4.7          1.6  Iris-versicolor
58            6.6          2.9           4.6          1.3  Iris-versicolor
..            ...          ...           ...          ...              ...
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

[64 rows x 5 columns]

In [107]:
# C. Group by species and compute:
# • Average sepal_length
# • Maximum petal_width
# • Standard deviation of sepal_width

In [108]:
# • Average sepal_length
df.groupby("species")["sepal_length"].mean()

species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: sepal_length, dtype: float64

In [109]:
# • Maximum petal_width
df.groupby("species")["petal_width"].max()

species
Iris-setosa        0.6
Iris-versicolor    1.8
Iris-virginica     2.5
Name: petal_width, dtype: float64

In [110]:
# • Standard deviation of sepal_width
df.groupby("species")["sepal_width"].std()

species
Iris-setosa        0.381024
Iris-versicolor    0.313798
Iris-virginica     0.322497
Name: sepal_width, dtype: float64

In [111]:
# D. Create a new column: "petal_ratio" = petal_length / petal_width
# • For each species, find the average petal_ratio.

In [112]:
#Create a new column: "petal_ratio" = petal_length / petal_width
df["petal_ratio"] = df["petal_length"] / df["petal_width"]

In [113]:
print(df["petal_ratio"])

0      7.000000
1      7.000000
2      6.500000
3      7.500000
4      7.000000
         ...
145    2.260870
146    2.631579
147    2.600000
148    2.347826
149    2.833333
Name: petal_ratio, Length: 150, dtype: float64

In [114]:
# • For each species, find the average petal_ratio.
df.groupby("species")["petal_ratio"].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

In [115]:
# Q2. Start by loading the TITANIC dataset. 
# A. Display only columns: Name, Sex, Age, Fare, Survived

In [116]:
df1 = pd.read_csv("Titanic-Dataset.csv")

In [117]:
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [118]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [119]:
# B. Select passengers who:
# • Are female
# • Fare > 30

In [120]:
# • Are female
df1[ df1["Sex"] == "female" ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [121]:
# • Fare > 30
df1[ df1["Fare"] > 30 ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [122]:
# C. Group by Pclass and compute:
# • Survival rate
# • Average Fare
# • Average Age

In [123]:
df1.groupby("Pclass")["Survived"].mean() *100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [124]:
df1.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [125]:
df1.groupby("Pclass")["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [126]:
# Level 1 – Data Understanding
# 1 Load the Iris dataset and determine how many unique species exist.
# 2 Find the average petal_length for each species.
# 3 Find the minimum, maximum, and average sepal_length for each species.
# 4 Identify rows where petal_length is greater than the dataset mean.
# 5 Count the number of samples for each species.
# 6 Create a new column: sepal_area = sepal_length * sepal_width.
# 7 Determine which species has the highest average sepal_area.

In [127]:
df = pd.read_csv("IRIS.csv")

In [128]:
df["species"].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [129]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [130]:
mean_petal = df["petal_length"].mean()

In [131]:
df[df["petal_length"] > mean_petal]

     sepal_length  sepal_width  petal_length  petal_width          species
50            7.0          3.2           4.7          1.4  Iris-versicolor
51            6.4          3.2           4.5          1.5  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor
53            5.5          2.3           4.0          1.3  Iris-versicolor
54            6.5          2.8           4.6          1.5  Iris-versicolor
..            ...          ...           ...          ...              ...
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

[93 rows x 5 columns]

In [132]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [133]:
df["species"].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [134]:
df["sepal_area"] = df["sepal_length"] * df["sepal_width"]

In [135]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,20.10
146,6.3,2.5,5.0,1.9,Iris-virginica,15.75
147,6.5,3.0,5.2,2.0,Iris-virginica,19.50
148,6.2,3.4,5.4,2.3,Iris-virginica,21.08
149,5.9,3.0,5.1,1.8,Iris-virginica,17.70

In [136]:
high_sepal = df.groupby("species")["sepal_area"].mean().idxmax()

In [137]:
high_sepal

'Iris-virginica'

In [138]:
# Level 2 – Data Cleaning & Transformation
# 1 Check the dataset for missing values.
# 2 Find duplicate rows and remove them.
# 3 Convert all column names to lowercase.
# 4 Normalize petal_length using the formula: (value − min) / (max − min).
# 5 Create a new categorical column 'petal_size': small (<2), medium (2–5), large (>5).
# 6 Count how many samples fall into each petal_size category.

In [139]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
sepal_area      0
dtype: int64

In [140]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [141]:
df.drop_duplicates()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,20.10
146,6.3,2.5,5.0,1.9,Iris-virginica,15.75
147,6.5,3.0,5.2,2.0,Iris-virginica,19.50
148,6.2,3.4,5.4,2.3,Iris-virginica,21.08
149,5.9,3.0,5.1,1.8,Iris-virginica,17.70

In [142]:
df.drop_duplicates()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,20.10
146,6.3,2.5,5.0,1.9,Iris-virginica,15.75
147,6.5,3.0,5.2,2.0,Iris-virginica,19.50
148,6.2,3.4,5.4,2.3,Iris-virginica,21.08
149,5.9,3.0,5.1,1.8,Iris-virginica,17.70

In [143]:
df.duplicated().sum()

np.int64(3)

In [144]:
df[df.duplicated()]

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
34,4.9,3.1,1.5,0.1,Iris-setosa,15.19
37,4.9,3.1,1.5,0.1,Iris-setosa,15.19
142,5.8,2.7,5.1,1.9,Iris-virginica,15.66

In [145]:
df = df.drop_duplicates()

In [146]:
df.duplicated().sum()

np.int64(0)

In [147]:
df.columns = df.columns.str.upper()

In [148]:
df

,SEPAL_LENGTH,SEPAL_WIDTH,PETAL_LENGTH,PETAL_WIDTH,SPECIES,SEPAL_AREA
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,20.10
146,6.3,2.5,5.0,1.9,Iris-virginica,15.75
147,6.5,3.0,5.2,2.0,Iris-virginica,19.50
148,6.2,3.4,5.4,2.3,Iris-virginica,21.08
149,5.9,3.0,5.1,1.8,Iris-virginica,17.70

In [149]:
df.columns = df.columns.str.lower()
df

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,20.10
146,6.3,2.5,5.0,1.9,Iris-virginica,15.75
147,6.5,3.0,5.2,2.0,Iris-virginica,19.50
148,6.2,3.4,5.4,2.3,Iris-virginica,21.08
149,5.9,3.0,5.1,1.8,Iris-virginica,17.70

In [150]:
# 4 Normalize petal_length using the formula: (value − min) / (max − min).
df["norma_petal_length"] =( df["petal_length"] - df["petal_length"].min() ) / (df["petal_length"].max() - df["petal_length"].min() )

In [151]:
print(df["norma_petal_length"].head())

0    0.067797
1    0.067797
2    0.050847
3    0.084746
4    0.067797
Name: norma_petal_length, dtype: float64

In [152]:
# 5 Create a new categorical column 'petal_size': small (<2), medium (2–5), large (>5).
import numpy as np
conditions = [ df["petal_length"] < 2 , (df["petal_length"] >=2) & (df["petal_length"] <=5 )  , df["petal_length"] >5      
]

choices = ["small", "medium", "large"]
df["petal_size"]=np.select(conditions, choices, default="unknow")

In [153]:
print(df["petal_size"].head())

0    small
1    small
2    small
3    small
4    small
Name: petal_size, dtype: str

In [154]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area,norma_petal_length,petal_size
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85,0.067797,small
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70,0.067797,small
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04,0.050847,small
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26,0.084746,small
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00,0.067797,small
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,20.10,0.711864,large
146,6.3,2.5,5.0,1.9,Iris-virginica,15.75,0.677966,medium
147,6.5,3.0,5.2,2.0,Iris-virginica,19.50,0.711864,large
148,6.2,3.4,5.4,2.3,Iris-virginica,21.08,0.745763,large
149,5.9,3.0,5.1,1.8,Iris-virginica,17.70,0.694915,large

In [155]:
df["petal_size"].value_counts()

petal_size
medium    58
small     48
large     41
Name: count, dtype: int64

In [156]:
df = pd.read_csv("IRIS.csv")

In [157]:
# 5 Create a new categorical column 'petal_size': small (<2), medium (2–5), large (>5).
import numpy as np
conditions = [ df["petal_length"] < 2 , (df["petal_length"] >=2) & (df["petal_length"] <=5 )  , df["petal_length"] >5      
]

choices = ["small", "medium", "large"]
df["petal_size"]=np.select(conditions, choices, default="unknow")

In [158]:
df["petal_size"].value_counts()

petal_size
medium    58
small     50
large     42
Name: count, dtype: int64

In [159]:
df.groupby("species")["petal_size"].value_counts()

species          petal_size
Iris-setosa      small         50
Iris-versicolor  medium        49
                 large          1
Iris-virginica   large         41
                 medium         9
Name: count, dtype: int64

In [160]:
df.groupby("species").agg({
    "petal_length" : "mean",
    "petal_width" : "mean",
    "sepal_length" : "mean",
    "sepal_width" : "mean",
})

                 petal_length  petal_width  sepal_length  sepal_width
species
Iris-setosa             1.464        0.244         5.006        3.418
Iris-versicolor         4.260        1.326         5.936        2.770
Iris-virginica          5.552        2.026         6.588        2.974

In [161]:
df.groupby("species").agg({
    "petal_length" : "max",
    "petal_width" : "min",
    "sepal_length" : "mean",
    "sepal_width" : "std",
})

                 petal_length  petal_width  sepal_length  sepal_width
species
Iris-setosa               1.9          0.1         5.006     0.381024
Iris-versicolor           5.1          1.0         5.936     0.313798
Iris-virginica            6.9          1.4         6.588     0.322497

In [162]:

avg_petal = df.groupby("species")["petal_length"].mean()
avg_petal.rank()

species
Iris-setosa        1.0
Iris-versicolor    2.0
Iris-virginica     3.0
Name: petal_length, dtype: float64

In [ ]:
summary = df.groupby("species").agg(
    avg_petal_length = ("petal_length", "mean"),
    avg_sepal_length = ("sepal_length", "mean"),
    sample_count = ("species", "count")
)

                 avg_petal_length  avg_sepal_length  sample_count
species
Iris-setosa                 1.464             5.006            50
Iris-versicolor             4.260             5.936            50
Iris-virginica              5.552             6.588            50

In [165]:
print(summary)

                 avg_petal_length  avg_sepal_length  sample_count
species
Iris-setosa                 1.464             5.006            50
Iris-versicolor             4.260             5.936            50
Iris-virginica              5.552             6.588            50